{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-status-service.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "platform-status-service.labels" . | nindent 4 }}
{{- end }}
