apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipyard-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SkyShineTH/Shipyard'
    targetRevision: main
    path: gitops/charts/frontend
    helm:
      valueFiles:
        - values.yaml
        - values.doks-public.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shipyard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
